// <auto-generated />
using EntityFrameworkCoreMultiTenancy;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameworkCoreMultiTenancy.Migrations
{
    [DbContext(typeof(Database))]
    partial class DatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0-preview.3.22175.1");

            modelBuilder.Entity("EntityFrameworkCoreMultiTenancy.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kind = "Dog",
                            Name = "Samson",
                            Tenant = "Khalid"
                        },
                        new
                        {
                            Id = 2,
                            Kind = "Dog",
                            Name = "Guiness",
                            Tenant = "Khalid"
                        },
                        new
                        {
                            Id = 3,
                            Kind = "Cat",
                            Name = "Grumpy Cat",
                            Tenant = "Internet"
                        },
                        new
                        {
                            Id = 4,
                            Kind = "Cat",
                            Name = "Mr. Bigglesworth",
                            Tenant = "Internet"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
